### ISSUE TITLE
CW tone in output

### ISSUE THREAD

**Issue by grbe1** [liuguangxi/gng#2]
This module is very interesting but we notice a continuous wave tone in its output:
![image](https://github.com/liuguangxi/gng/assets/162599007/f92dc2f3-745c-4337-abe1-6a4cc6cc217b)

**Comment by liuguangxi** [comment]
Could you explain more detailed how to generate the signal in the screenshot?
It seems that the continuous wave tone was caused by DC offset in the transmitter chain.

**Comment by grbe1** [comment]
This is probably our mistake. We realize now that the FFT is not large enough to show the DC component over a long period of time, so a residual DC value is observed based on the size of the FFT .
EDIT: I'm still looking at this... not quite sure where the DC was coming from but its entirely digital - i.e. digital signal with noise added in from the gng and then analyzed. Our DSP engineer has created a new noise module without this DC component so it looks like it was coming from the gng module. I may not have time to continue to far with this but I'll try to have some more information.

**Comment by liuguangxi** [comment]
You may use MATLAB to analyze the spectral characteristic of gng module, refer to the code in matlab directory. The output data of MATLAB code should be identical to RTL code, if both were given the same seed value.
There exists a slight DC component in the simulation result of gng, but it seems not the problem with the algorithm itself.

**Comment by grbe1** [comment]
Yes, so I got Octave to do an FFT on the HDL simulation output and there is indeed a DC component the becomes larger for larger FFT sizes. So this is an issue but I don't know where the DC is coming from. I think that's all the time I can spend on this. I'll be following to see if the issue is fixed in the future - Regards, Greg.
